## 前処理
- バス・トイレ ： 専用バス/専用トイレ/浴室乾燥機/温水洗浄便座/追焚機能/洗面台独立
- キッチン ： ガスコンロ数/IHコンロ数/給湯/カウンターキッチン/システムキッチン/独立キッチン/L字キッチン
- 放送・通信 : インターネット使用量無料/インターネット対応or光ファイバーどちらか存在で1/テレビ(CATV or BSアンテナ or CSアンテナ)/
- 室内設備 : 個数

In [182]:
import numpy as np
import pandas as pd

In [183]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
sample = pd.read_csv('sample_submit.csv', header=None)

In [184]:
train.head(1)

,id,賃料,所在地,アクセス,間取り,築年数,方角,面積,所在階,バス・トイレ,キッチン,放送・通信,室内設備,駐車場,周辺環境,建物構造,契約期間
0,1,75000,東京都北区滝野川３丁目,都営三田線\t西巣鴨駅\t徒歩4分\t\t埼京線\t板橋駅\t徒歩14分\t\t都電荒川線\...,1K,9年9ヶ月,南東,20.01m2,1階／12階建,専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー／\t浴室乾燥機\t／\t温水洗浄便座,ガスコンロ／\tコンロ2口／\tシステムキッチン\t／\t給湯,インターネット対応／\tCATV／\tCSアンテナ／\tBSアンテナ,エアコン付\tシューズボックス／\tバルコニー／\tフローリング／\t室内洗濯機置場／\t敷...,駐輪場\t空有,【小学校】 495m\t【大学】 461m\t【小学校】 962m\t【公園】 1103m\...,RC（鉄筋コンクリート）,2年間

## バス・トイレ
- 専用バス/専用トイレ/浴室乾燥機/温水洗浄便座/追焚機能/洗面台独立

In [185]:
train['バス・トイレ'].value_counts().head(10)

専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー／\t追焚機能／\t浴室乾燥機\t／\t温水洗浄便座／\t洗面台独立／\t脱衣所    4606
専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー／\t浴室乾燥機\t／\t温水洗浄便座／\t洗面台独立／\t脱衣所           2936
専用バス／\t専用トイレ／\tシャワー                                                      2133
専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー                                            1495
専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー／\t追焚機能／\t浴室乾燥機\t／\t温水洗浄便座／\t洗面台独立           873
シャワー                                                                      849
専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー／\t洗面台独立／\t脱衣所                               802
バス・トイレ別／\tシャワー／\t追焚機能／\t浴室乾燥機\t／\t温水洗浄便座／\t洗面台独立                          795
専用バス／\t専用トイレ／\tバス・トイレ別／\tシャワー／\t浴室乾燥機\t／\t温水洗浄便座／\t洗面台独立                  708
バス・トイレ別／\tシャワー                                                            656
Name: バス・トイレ, dtype: int64

In [186]:
train_bath = train["バス・トイレ"].str.split("\t", expand=True)
train_bath

,0,1,2,3,4,5,6,7,8,9
0,専用バス／,専用トイレ／,バス・トイレ別／,シャワー／,浴室乾燥機,／,温水洗浄便座,None,None,None
1,専用トイレ／,シャワー／,温水洗浄便座,None,None,None,None,None,None,None
2,専用バス／,専用トイレ／,バス・トイレ別／,シャワー／,浴室乾燥機,／,温水洗浄便座／,洗面台独立／,脱衣所,None
3,専用バス／,専用トイレ／,バス・トイレ別／,シャワー／,温水洗浄便座／,洗面台独立,None,None,None,None
4,専用バス／,専用トイレ／,バス・トイレ別／,シャワー／,追焚機能,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...
31465,専用バス／,専用トイレ／,バス・トイレ別／,シャワー／,追焚機能／,洗面台独立,None,None,None,None
31466,専用バス／,専用トイレ／,シャワー,None,None,None,None,None,None,None
31467,バス・トイレ別／,シャワー／,追焚機能／,温水洗浄便座,None,None,None,None,None,None
31468,専用バス／,専用トイレ／,バス・トイレ別／,シャワー／,洗面台独立,None,None,None,None,None
31469,専用バス／,専用トイレ／,バス・トイレ別／,シャワー,None,None,None,None,None,None

In [187]:
bath_calums = ['専用バス', '専用バス／', '専用トイレ', '専用トイレ／','バス・トイレ別','バス・トイレ別／','シャワー','シャワー／',
              '追焚機能', '追焚機能／', '浴室乾燥機', '浴室乾燥機／','温水洗浄便座','温水洗浄便座／','洗面台独立','洗面台独立／']

In [188]:
# カルムの数
count=len(train_bath.columns)

# bath_calumsの追加
for _, colname in enumerate(bath_calums):
    train_bath[colname]=0
        
    for k in range(count):
        train_bath.loc[train_bath[k]==colname, colname]=1 
        
# 必要なカルムのみ        
train_bath = train_bath[bath_calums].copy()

In [189]:
#train_bath[]=train_bath[]+train_bath[]
train_bath['専用バス']=train_bath['専用バス']+train_bath['専用バス／']
train_bath['専用トイレ']=train_bath['専用トイレ']+train_bath['専用トイレ／']
train_bath['バス・トイレ別']=train_bath['バス・トイレ別']+train_bath['バス・トイレ別／']
train_bath['シャワー']=train_bath['シャワー']+train_bath['シャワー／']
train_bath['追焚機能']=train_bath['追焚機能']+train_bath['追焚機能／']
train_bath['浴室乾燥機']=train_bath['浴室乾燥機']+train_bath['浴室乾燥機／']
train_bath['温水洗浄便座']=train_bath['温水洗浄便座']+train_bath['温水洗浄便座／']
train_bath['洗面台独立']=train_bath['洗面台独立']+train_bath['洗面台独立／']

In [190]:
train_bath.drop(['専用バス／', '専用トイレ／', 'バス・トイレ別／', 'シャワー／', '追焚機能／', '浴室乾燥機／', '温水洗浄便座／',
                 '洗面台独立／'], axis=1)

       専用バス  専用トイレ  バス・トイレ別  シャワー  追焚機能  浴室乾燥機  温水洗浄便座  洗面台独立
0         1      1        1     1     0      1       1      0
1         0      1        0     1     0      0       1      0
2         1      1        1     1     0      1       1      1
3         1      1        1     1     0      0       1      1
4         1      1        1     1     1      0       0      0
...     ...    ...      ...   ...   ...    ...     ...    ...
31465     1      1        1     1     1      0       0      1
31466     1      1        0     1     0      0       0      0
31467     0      0        1     1     1      0       1      0
31468     1      1        1     1     0      0       0      1
31469     1      1        1     1     0      0       0      0

[31470 rows x 8 columns]

## キッチン
- ガスコンロ数/IHコンロ数/給湯/カウンターキッチン/システムキッチン/独立キッチン/L字キッチン

In [191]:
train['キッチン'].value_counts().head(10)

ガスコンロ／\tコンロ2口／\tシステムキッチン\t／\t給湯                  6016
ガスコンロ／\tコンロ2口／\t給湯                               2272
ガスコンロ／\tコンロ3口／\tシステムキッチン\t／\t給湯                  1606
給湯                                               1328
ガスコンロ／\tコンロ2口／\tシステムキッチン\t／\t給湯／\t独立キッチン         1299
ガスコンロ／\tコンロ3口／\tシステムキッチン\t／\tカウンターキッチン\t／\t給湯    1249
ガスコンロ／\t給湯                                        933
ガスコンロ／\tコンロ2口／\tシステムキッチン                          778
IHコンロ\t／\tコンロ2口／\tシステムキッチン\t／\t給湯                 707
ガスコンロ／\tコンロ1口／\t給湯                                624
Name: キッチン, dtype: int64

In [192]:
train_kitchen = train["キッチン"].str.split("\t", expand=True)
train_kitchen

            0         1         2     3     4     5     6     7     8     9
0      ガスコンロ／    コンロ2口／  システムキッチン     ／    給湯  None  None  None  None  None
1      ガスコンロ／  システムキッチン         ／    給湯  None  None  None  None  None  None
2      ガスコンロ／    コンロ2口／  システムキッチン     ／    給湯  None  None  None  None  None
3      ガスコンロ／        給湯      None  None  None  None  None  None  None  None
4         給湯／    独立キッチン      None  None  None  None  None  None  None  None
...       ...       ...       ...   ...   ...   ...   ...   ...   ...   ...
31465  ガスコンロ／    コンロ2口／        給湯  None  None  None  None  None  None  None
31466  ガスコンロ／    コンロ1口／        給湯  None  None  None  None  None  None  None
31467  ガスコンロ／     コンロ2口      None  None  None  None  None  None  None  None
31468  ガスコンロ／  システムキッチン         ／    給湯  None  None  None  None  None  None
31469  ガスコンロ／        給湯      None  None  None  None  None  None  None  None

[31470 rows x 10 columns]

In [193]:
kitchen_calums =['ガスコンロ', 'ガスコンロ／', 'コンロ2口', 'コンロ2口／', 'コンロ3口', 'コンロ3口／', 'IHコンロ', 'IHコンロ／',
                 '給湯', '給湯／', 'カウンターキッチン', 'カウンターキッチン／', 'システムキッチン', 'システムキッチン／',
                 '独立キッチン', '独立キッチン／', 'L字キッチン', 'L字キッチン／']

In [194]:
# カルムの数
count=len(train_kitchen.columns)

# kitchen_calumsの追加
for _, colname in enumerate(kitchen_calums):
    train_kitchen[colname]=0
        
    for k in range(count):
        train_kitchen.loc[train_kitchen[k]==colname, colname]=1 
        
# 必要なカルムのみ        
train_kitchen = train_kitchen[kitchen_calums].copy()

In [195]:
#train_kitchen[]=train_kitchen[]+train_kitchen[]
train_kitchen['ガスコンロ']=train_kitchen['ガスコンロ']+train_kitchen['ガスコンロ／']
train_kitchen['コンロ2口']=train_kitchen['コンロ2口']+train_kitchen['コンロ2口／']
train_kitchen['コンロ3口']=train_kitchen['コンロ3口']+train_kitchen['コンロ3口／']
train_kitchen['IHコンロ']=train_kitchen['IHコンロ']+train_kitchen['IHコンロ／']
train_kitchen['給湯']=train_kitchen['給湯']+train_kitchen['給湯／']
train_kitchen['カウンターキッチン']=train_kitchen['カウンターキッチン']+train_kitchen['カウンターキッチン／']
train_kitchen['システムキッチン']=train_kitchen['システムキッチン']+train_kitchen['システムキッチン／']
train_kitchen['独立キッチン']=train_kitchen['独立キッチン']+train_kitchen['独立キッチン／']
train_kitchen['L字キッチン']=train_kitchen['L字キッチン']+train_kitchen['L字キッチン／']

In [197]:
train_kitchen.drop(['ガスコンロ／', 'コンロ2口／','コンロ3口／', 'IHコンロ／', '給湯／', 'カウンターキッチン／', 'システムキッチン／','独立キッチン／', 'L字キッチン／'], axis=1)

       ガスコンロ  コンロ2口  コンロ3口  IHコンロ  給湯  カウンターキッチン  システムキッチン  独立キッチン  L字キッチン
0          1      1      0      0   1          0         1       0       0
1          1      0      0      0   1          0         1       0       0
2          1      1      0      0   1          0         1       0       0
3          1      0      0      0   1          0         0       0       0
4          0      0      0      0   1          0         0       1       0
...      ...    ...    ...    ...  ..        ...       ...     ...     ...
31465      1      1      0      0   1          0         0       0       0
31466      1      0      0      0   1          0         0       0       0
31467      1      1      0      0   0          0         0       0       0
31468      1      0      0      0   1          0         1       0       0
31469      1      0      0      0   1          0         0       0       0

[31470 rows x 9 columns]